### ISSUE TITLE
Add @medv/finder

### ISSUE THREAD

**Issue by antonmedv** [fczbkk/css-selector-generator-benchmark#7]
Hi,

Created new lib: https://github.com/antonmedv/finder

Check it out!

**Comment by antonmedv** [comment]
ping @fczbkk :)

**Comment by fczbkk** [comment]
@antonmedv Sorry about the delay. I finally got to add your library to the benchmark:

https://github.com/fczbkk/css-selector-generator-benchmark#antonmedv-finder
